services:
  postgres:
    image: postgres:17-alpine
    container_name: escala-shekinah-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: escala_shekinah
      POSTGRES_USER: escala_user
      POSTGRES_PASSWORD: escala_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
